import { SelectableValue, TimeOption } from '@grafana/data';

export const quickOptions: TimeOption[] = [
  { from: 'now-5m', to: 'now', display: '最近 5 分钟' },
  { from: 'now-15m', to: 'now', display: '最近 15 分钟' },
  { from: 'now-30m', to: 'now', display: '最近 30 分钟' },
  { from: 'now-1h', to: 'now', display: '最近 1 小时' },
  { from: 'now-3h', to: 'now', display: '最近 3 小时' },
  { from: 'now-6h', to: 'now', display: '最近 6 小时' },
  { from: 'now-12h', to: 'now', display: '最近 12 小时' },
  { from: 'now-24h', to: 'now', display: '最近 24 小时' },
  { from: 'now-2d', to: 'now', display: '最近 2 天' },
  { from: 'now-7d', to: 'now', display: '最近 7 天' },
  { from: 'now-30d', to: 'now', display: '最近 30 天' },
  { from: 'now-90d', to: 'now', display: '最近 90 天' },
  { from: 'now-6M', to: 'now', display: '最近 6 个月' },
  { from: 'now-1y', to: 'now', display: '最近 1 年' },
  { from: 'now-2y', to: 'now', display: '最近 2 年' },
  { from: 'now-5y', to: 'now', display: '最近 5 年' },
  { from: 'now-1d/d', to: 'now-1d/d', display: '昨天' },
  { from: 'now-2d/d', to: 'now-2d/d', display: '前天' },
  { from: 'now-7d/d', to: 'now-7d/d', display: '上周的今天' },
  { from: 'now-1w/w', to: 'now-1w/w', display: '前一周' },
  { from: 'now-1M/M', to: 'now-1M/M', display: '前一月' },
  { from: 'now-1Q/fQ', to: 'now-1Q/fQ', display: '上一财季' },
  { from: 'now-1y/y', to: 'now-1y/y', display: '前一年' },
  { from: 'now-1y/fy', to: 'now-1y/fy', display: '上一财年' },
  { from: 'now/d', to: 'now/d', display: '今天' },
  { from: 'now/d', to: 'now', display: '到目前为止' },
  { from: 'now/w', to: 'now/w', display: '本周' },
  { from: 'now/w', to: 'now', display: '这周到目前为止' },
  { from: 'now/M', to: 'now/M', display: '本月' },
  { from: 'now/M', to: 'now', display: '这月到目前为止' },
  { from: 'now/y', to: 'now/y', display: '本年' },
  { from: 'now/y', to: 'now', display: '这年到目前为止' },
  { from: 'now/fQ', to: 'now', display: '这个财政季度到目前为止' },
  { from: 'now/fQ', to: 'now/fQ', display: '本财政季度' },
  { from: 'now/fy', to: 'now', display: '本财政年度至今' },
  { from: 'now/fy', to: 'now/fy', display: '本财政年度' },
];

export const monthOptions: Array<SelectableValue<number>> = [
  { label: 'January', value: 0 },
  { label: 'February', value: 1 },
  { label: 'March', value: 2 },
  { label: 'April', value: 3 },
  { label: 'May', value: 4 },
  { label: 'June', value: 5 },
  { label: 'July', value: 6 },
  { label: 'August', value: 7 },
  { label: 'September', value: 8 },
  { label: 'October', value: 9 },
  { label: 'November', value: 10 },
  { label: 'December', value: 11 },
];
